import { Metadata } from "next";
import Nav from "./(components)/Nav";
import { Inter, Lato } from "next/font/google";
import "../global.css";
import Footer from "./(components)/Footer";
import ToastProvider from "./provider/ToastProvider";
export const metadata: Metadata = {
  title: {
    default: "Apps",
    template: "%s | Apps",
  },
  description: "Generated by Next.js",
};

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});
export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        <ToastProvider />
        <Nav />

        {children}
        <Footer />
      </body>
    </html>
  );
}
